config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    resources :cars   #создаеются сразу show edit в контроллере 
    root 'cars#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
	has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action  :find_car, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @cars = Car.all.order("created_at DESC")  # сортировка по алфавиту
    else
      @category_id = Category.find_by(name: params[:category]).id
      @cars = Car.where(:category_id => @category_id).order("created_at DESC")
    end
  end


  def show
  end

  def new
    @car = current_user.cars.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create

    @car = current_user.cars.build(car_params)
    @car.category_id = params[:categoty_id]
    if @car.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
     @car.category_id = params[:categoty_id]
  end

  def update
     @car.category_id = params[:categoty_id]
    if @car.update(car_params)
      redirect_to car_path(@car)

    else
      render 'edit'
    end
  end

  def destroy
    @car.destroy
    redirect_to root_path
  end

  private

  def car_params
    params.require(:car).permit(:model, :brand, :number, :year, :mileage, :categoty_id)
  end

  def find_car
    @car  = Car.find(params[:id]) #при клике на первый автомобиль  id = 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for @car, :html => {:multipart => true}   do |f|  %>
<%= select_tag(:categoty_id, options_for_select(@categories), :prompt => "Select category")   %>
<%= f.input :model, label: "Cars`name"   %>
<%= f.input :brand   %>
<%= f.input :number   %>
<%= f.input :year  %>
<%= f.input :mileage  %>
<%= f.button :submit %>

<% end %>

app/views/cars/edit.html.erb
<h1>EDIT CAR</h1>

<%= simple_form_for @car, :html => {:multipart => true} do |f|  %>
	<%= f.select :category_id, @categories  %>
	<%= f.input :model, label: "Cars`name"   %>
	<%= f.input :brand   %>
	<%= f.input :number   %>
	<%= f.input :year  %>
	<%= f.input :mileage  %>
	<%= f.button :submit %>
<% end %>

app/views/cars/index.html.erb
<h1 class="current-category"><%= params[:category]%> </h1>

<% if @cars.count == 0 %>
	<h1>В данной категории нет автомобилей</h1>
<% else %> 
	<% @cars.each do |car| %>
		<h2> <%=  link_to car.model, car_path(car)  %> </h2>
	<%end%>
<%end%>

app/views/cars/new.html.erb
<h1>NEW CAR</h1>

<%= render 'form'  %>

app/views/cars/show.html.erb
<h1> <%=  	@car.model	%></h1>
<h2> <%=  	@car.brand	%></h2>
<h2> <%=  	@car.year	%></h2>
<h2> <%=  	@car.mileage %></h2>
<h4>Category: <%= @car.category.name %></h4>
<%= link_to "back", root_path %>

<% if user_signed_in? %>
	<% if current_user.id == 5  %>
		<%= link_to "Edit", edit_car_path(@car) %>
		<%= link_to "Delete", car_path(@car), method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render "shared/navbar" %>
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class = "navbar navbar-default">
  <div class = "container">
    <div class = "navbar-header">
      <%= link_to "Cars",root_path, class: "navbar-brand"%>       
    </div>   
<ul class = "nav navbar-nav">
  <li> <%= link_to "Sign up", new_user_registration_path %></li>
  <% if user_signed_in? %>
    <li> <%= link_to "Sign out",destroy_user_session_path, method: :delete %></li>
  <%else%>
    <li> <%= link_to "Log In", new_user_session_path %></li>
  <%end%>

 <ul class="nav navbar-nav navbar-right">

    <% Category.all.each do |category| %>
        <li class ="<%= 'active' if params[:category] == category.name %>"> 
          <%= link_to category.name, cars_path(category: category.name), class: "link" %>
        </li>
    <% end %>
  </ul>
  <% if current_user.try(:admin?) %>
    <li> <%= link_to "Cash", root_path %> </li>
    <li> <%= link_to "Add fine", root_path %> </li>
    <li> <%= link_to "Clients base", root_path %> </li>
    <li> <%= link_to "Cars base", root_path %></li>
  <%else%>
    <li><%= link_to "Booking car", root_path %></li>
    <li><%- link_to "Fines, you have.", root_path %></li>
    <%end%>
</ul>
<ul class = "nav navbar-nav navbar-right">
  <% if current_user.try(:admin?) %>
   <li><%= link_to "Add Car", new_car_path  %></li>
  <%end%>
 
</ul>
  </div>
</nav>